#
# securememo.app
# Deploy from Main branch > Cloudflare main
# Deploy from Development branch > Cloudflare dev Worker
#

#This is for Worker Paid-tier.
#CF Pro-tier allows 2 WAF ratelimit configurations.
#[rate_limits]
#binding = "API_RATE_LIMITER"
#period = 60 
#requests_per_period = 100  

# Disable workers.dev by default (safety)
workers_dev = false

name = "securememo"
main = "src/index.js"
compatibility_date = "2025-01-01"

# Static assets
[assets]
directory = "./public"

# Production environment
[env.production]
name = "securememo"
workers_dev = false

# Production environment - enable cron triggers for cleanup
[env.production.triggers]
crons = ["0 */1 * * *"]  # Run cleanup every 1 hours

# Production D1 database
[[env.production.d1_databases]]
binding = "DB"
database_name = "my-database"
database_id = "13dc8e43-a1bb-4414-9c52-f77296261b96"

# Production environment variables
[env.production.vars]
LOG_LEVEL = "INFO"

# Production routes for the Worker
[[env.production.routes]]
pattern = "securememo.app/*"
zone_name = "securememo.app"

# Logs are enabled
[observability.logs]
enabled = true

# Development environment
[env.dev]
name = "securememo-dev"
workers_dev = true # enable on deploy, behind Cloudflare Zero Trust

# Development environment variables
[env.dev.vars]
LOG_LEVEL = "DEBUG"

# Development D1 database
[[env.dev.d1_databases]]
binding = "DB"
database_name = "securememo-dev"
database_id = "159356d9-9eee-4f53-99e6-1b252b0df8df"

# Development environment
[env.dev.triggers]
crons = []

# Disable previews
[previews]
enabled = false