name: CI

on:
  push:
    branches: [ main, features, feature/** ]
  pull_request:
    branches: [ main, features ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Dependency audit (fail on high)
        run: npm run audit:high

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: |
          npm test
          npm run test:lifecycle

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        with:
          coverage-reports: coverage/lcov.info

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results
          if-no-files-found: ignore
